### ISSUE TITLE
Huvec data is missing at synapse

### ISSUE THREAD

**Issue by DominiquePaul** [biomed-AI/TransEPI#1]
Hi, 
in the readme section "Quickstart" you mention that the data has to be downloaded from synapse.org and that the filepaths need to be replaced with absolute file paths in the file `./data/genomic_data/CTCF_DNase_6histone.500.json`.

In the file `./data/genomic_data/CTCF_DNase_6histone.500.json` there is a group of files referred to as "HUVEC". While, these files appear by name at [Synapse landing page](https://www.synapse.org/#!Synapse:syn26156164/wiki/612650) there is no folder in the files section which contains these files.

Could you provide a link to download these files to run and reproduce the model? 

Thanks a lot!

<img width="1398" alt="Screenshot 2022-09-28 at 17 02 57" src="https://user-images.githubusercontent.com/16308215/192814536-33156012-6afb-4384-ab0e-52f240997fbf.png">

**Comment by chenkenbio** [comment]
Hello, sorry for the delay in replying you. I have just uploaded the processed files of HUVEC to [synapse](https://www.synapse.org/#!Synapse:syn39554159). Feel free to contact me if you have any other questions. Thank you for your interest in our work!

**Comment by DominiquePaul** [comment]
Thanks!
